apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: example-foo-reconcile
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: $DOCKER_USER/sample-controller
          serviceAccountName: example-foo-reconcile