apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databases.cloudant.seed.ibm.com
spec:
  group: cloudant.seed.ibm.com
  version: v1alpha1
  names:
    categories:
    - all
    - seed
    kind: Database
    plural: databases
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            secretRef:
              type: string
            name:
              type: string
